const { Client, LocalAuth } = require('whatsapp-web.js');
const qrcode = require('qrcode-terminal');

class WhatsAppClient {
  constructor() {
    this.client = new Client({
      authStrategy: new LocalAuth({
        dataPath: '.wwebjs_auth'
      }),
      puppeteer: {
        headless: true,
        args: [
          '--no-sandbox',
          '--disable-setuid-sandbox',
          '--disable-dev-shm-usage',
          '--disable-accelerated-2d-canvas',
          '--no-first-run',
          '--no-zygote',
          '--single-process',
          '--disable-gpu'
        ]
      }
    });

    this.isReady = false;
    this.messageHandlers = [];
  }

  async initialize() {
    return new Promise((resolve, reject) => {
      this.client.on('qr', (qr) => {
        console.log('📱 Scan this QR code with WhatsApp:');
        qrcode.generate(qr, { small: true });
        console.log('\nOpen WhatsApp > Settings > Linked Devices > Link a Device');
      });

      this.client.on('authenticated', () => {
        console.log('✅ WhatsApp authenticated');
      });

      this.client.on('auth_failure', (msg) => {
        console.error('❌ WhatsApp authentication failed:', msg);
        reject(new Error('Authentication failed'));
      });

      this.client.on('ready', () => {
        console.log('✅ WhatsApp client is ready!');
        this.isReady = true;
        resolve();
      });

      this.client.on('disconnected', (reason) => {
        console.log('❌ WhatsApp disconnected:', reason);
        this.isReady = false;
      });

      this.client.on('message', async (msg) => {
        await this.handleMessage(msg);
      });

      this.client.initialize().catch(reject);
    });
  }

  async handleMessage(msg) {
    if (msg.from.includes('@g.us') || msg.isStatus) {
      return;
    }

    if (msg.fromMe) {
      return;
    }

    console.log(`📨 Message from ${msg.from}: ${msg.body}`);

    for (const handler of this.messageHandlers) {
      try {
        await handler(msg);
      } catch (error) {
        console.error('Error in message handler:', error);
      }
    }
  }

  onMessage(handler) {
    this.messageHandlers.push(handler);
  }

  async sendMessage(messageObject, text) {
    try {
      if (!text || typeof text !== 'string') {
        console.error('❌ Invalid message text:', text);
        return false;
      }

      await new Promise(resolve => setTimeout(resolve, 1000));

      console.log('📤 Attempting to send message...');
      console.log('   Chat ID:', messageObject.from);
      console.log('   Message length:', text.length);

      const chat = await messageObject.getChat();
      await chat.sendMessage(text);

      console.log(`✅ Message sent successfully to ${messageObject.from}`);
      return true;

    } catch (error) {
      console.error('❌ Error sending message:', error.message);

      try {
        console.log('🔄 Trying fallback method...');
        await this.client.sendMessage(messageObject.from, text);
        console.log(`✅ Fallback successful for ${messageObject.from}`);
        return true;
      } catch (fallbackError) {
        console.error('❌ Fallback also failed:', fallbackError.message);
        return false;
      }
    }
  }

  async sendInvoice(messageObject, invoice) {
    const message = this.formatInvoice(invoice);
    return await this.sendMessage(messageObject, message);
  }

  formatInvoice(invoice) {
    let message = `📄 *INVOICE ${invoice.invoice_number}*\n\n`;
    message += `*To:* ${invoice.customer_name}\n`;
    message += `*Date:* ${new Date(invoice.created_at).toLocaleDateString()}\n`;

    if (invoice.due_date) {
      message += `*Due Date:* ${new Date(invoice.due_date).toLocaleDateString()}\n`;
    }

    message += `\n*Items:*\n`;

    if (invoice.items && Array.isArray(invoice.items)) {
      invoice.items.forEach(item => {
        message += `• ${item.description}: ₦${parseFloat(item.amount).toLocaleString()}\n`;
      });
    }

    message += `\n*Total Amount:* ₦${parseFloat(invoice.amount).toLocaleString()}\n`;

    if (invoice.notes) {
      message += `\n*Notes:* ${invoice.notes}\n`;
    }

    message += `\n_Generated by ${process.env.BUSINESS_NAME}_`;

    return message;
  }

  formatCustomerList(customers) {
    if (customers.length === 0) {
      return "You don't have any customers yet. Add one by saying 'Add customer [name]'";
    }

    let message = `👥 *Your Customers* (${customers.length})\n\n`;
    customers.slice(0, 20).forEach((customer, index) => {
      message += `${index + 1}. ${customer.name}`;
      if (customer.phone) {
        message += ` - ${customer.phone}`;
      }
      message += '\n';
    });

    if (customers.length > 20) {
      message += `\n_...and ${customers.length - 20} more_`;
    }

    return message;
  }

  formatInvoiceList(invoices) {
    if (invoices.length === 0) {
      return "You don't have any invoices yet. Create one by saying 'Create invoice for [customer]'";
    }

    let message = `📊 *Your Recent Invoices*\n\n`;
    invoices.slice(0, 10).forEach(inv => {
      const status = inv.status === 'paid' ? '✅' : inv.status === 'pending' ? '⏳' : '📝';
      message += `${status} ${inv.invoice_number}\n`;
      message += `   ${inv.customer_name}: ₦${parseFloat(inv.amount).toLocaleString()}\n`;
      message += `   ${new Date(inv.created_at).toLocaleDateString()}\n\n`;
    });

    return message;
  }

  getPhoneNumber(msg) {
    return msg.from.replace('@c.us', '').replace('@lid', '');
  }
}

module.exports = WhatsAppClient;